# Generated by Django 4.1.3 on 2022-11-30 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_itemproduct_shoppingcart_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
