# Generated by Django 4.1.3 on 2022-12-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_buy_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='shoppingCart',
            new_name='shoppingcart',
        ),
    ]
